<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <RootNamespace>AstraSystemsRental.Gateway</RootNamespace>
    <AssemblyName>AstraSystemsRental.Gateway</AssemblyName>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="AstraSystemsRental.Base" />
    <PackageReference Include="Microsoft.AspNetCore.OpenApi" />
    <PackageReference Include="Scalar.AspNetCore" />
    <PackageReference Include="Yarp.ReverseProxy" />
  </ItemGroup>

</Project>
