<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <RootNamespace>AstraSystemsRental.Reports.Api</RootNamespace>
    <AssemblyName>AstraSystemsRental.Reports.Api</AssemblyName>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="AstraSystemsRental.Base" />
    <PackageReference Include="Microsoft.AspNetCore.OpenApi" />
    <PackageReference Include="Scalar.AspNetCore" />
    <PackageReference Include="Microsoft.Extensions.Http.Resilience" />
  </ItemGroup>

</Project>
